#! /usr/bin/env bash

scriptBaseName=$(basename "$0")

printHelp() {
    echo
    echo "Usage: $scriptBaseName -t <tracefile path/name> [-m]"
    echo -e "\t-t: the trace file path/name to use"
    echo -e "\t-m: optional switch to dump the mouse/key bindings for gnuplot\n"
    echo
}
while getopts ":t:hm" flag; do
    case ${flag} in
        t)
            traceFile=${OPTARG};;
        m)
            keyBindingLocation=$(dirname "$0")/gnuplot.keybindings.txt
            echo "mouse and keybindings: "
            cat $keyBindingLocation
            echo
            echo "NOTE: this file is located at: $keyBindingLocation"
            echo
            exit 0;;
        h)
            printHelp
            exit 0;;
        \?)
            echo "ERROR: must provide a trace file (csv)"
            printHelp
            exit 4;;
    esac
done
if [ -z "$traceFile" ]; then
    echo "ERROR: must provide a trace file (csv file): -t <traceFile>"
    printHelp
    exit 2
fi
if [ ! -f $traceFile ]; then
    echo "ERROR: cannot open traceFile: $traceFile"
    printHelp
    exit 3
fi
gnuplot -c ~/utilities4905/trace.windows.csv $traceFile
